import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function DecoBackground() {
  // SVG pattern inspired by deco-geometric-glow, with dark lines and subtle glow
  return (
    <div
      aria-hidden="true"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 0,
        pointerEvents: "none",
        width: "100vw",
        height: "100vh",
        opacity: 0.7,
      }}
    >
      <svg width="100%" height="100%" viewBox="0 0 1920 1080" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ position: "absolute", inset: 0 }}>
        <g opacity="0.16">
          <rect x="0" y="0" width="1920" height="1080" fill="none" />
          <g filter="url(#glow)">
            {/* Diagonal lines */}
            <path d="M0 0L1920 1080M1920 0L0 1080" stroke="#23232a" strokeWidth="2" />
            {/* Central cross */}
            <path d="M960 0V1080M0 540H1920" stroke="#23232a" strokeWidth="2" />
            {/* Concentric circles */}
            <circle cx="960" cy="540" r="320" stroke="#23232a" strokeWidth="2" />
            <circle cx="960" cy="540" r="480" stroke="#23232a" strokeWidth="1.5" />
            <circle cx="960" cy="540" r="640" stroke="#23232a" strokeWidth="1" />
            {/* Radiating lines */}
            <path d="M480 540L1440 540" stroke="#23232a" strokeWidth="1" />
            <path d="M960 160L960 920" stroke="#23232a" strokeWidth="1" />
            <path d="M320 1080L1600 0" stroke="#23232a" strokeWidth="1" />
            <path d="M1600 1080L320 0" stroke="#23232a" strokeWidth="1" />
          </g>
        </g>
        <defs>
          <filter id="glow" x="-100" y="-100" width="2120" height="1280" filterUnits="userSpaceOnUse">
            <feGaussianBlur stdDeviation="16" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>
      </svg>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ position: "relative", minHeight: "100vh" }}
      >
        <DecoBackground />
        <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
      </body>
    </html>
  );
}
